# Generated by Django 2.1.7 on 2019-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20190224_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pays',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
