# Generated by Django 2.1.7 on 2019-04-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20190402_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_modified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
