# Generated by Django 2.1.2 on 2018-12-15 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('intitule', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('autre_description', models.TextField(max_length=1024)),
                ('statut', models.CharField(choices=[('LIBRE', 'LIBRE'), ('RESERVE', 'RESERVE'), ('OCCUPE', 'OCCUPE'), ('BIENTOT LIBRE', 'BIENTOT_LIBRE')], default='LIBRE', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('codebanque', models.CharField(max_length=25, unique=True)),
                ('libbanque', models.CharField(max_length=100)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('ice', models.CharField(max_length=100, null=True)),
                ('ice_number', models.CharField(max_length=50, null=True)),
                ('ice_relation', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComposantAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('libelle', models.CharField(max_length=50)),
                ('utilite', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('reference_bail', models.CharField(max_length=50)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('periodicite', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('montant_bail', models.IntegerField()),
                ('statut', models.CharField(choices=[('ANNULE', 'ANNULE'), ('PROPOSITION', 'PROPOSITION'), ('EN COURS', 'EN COURS'), ('RESILIE', 'RESILIE'), ('TERME', 'TERME')], default='PROPOSITION', max_length=6)),
                ('caution_loyer', models.IntegerField()),
                ('caution_eau', models.IntegerField()),
                ('caution_electricite', models.IntegerField()),
                ('observation', models.CharField(max_length=256, null=True)),
                ('tacite_reconduction', models.BooleanField(default=True)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Appartement')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('intitule', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512, null=True)),
                ('adresse', models.CharField(max_length=512, null=True)),
                ('jour_emission_facture', models.IntegerField(default=5)),
                ('jour_valeur_facture', models.IntegerField(default=5)),
                ('ville', models.CharField(max_length=128, null=True)),
                ('quartier', models.CharField(max_length=128, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('ref_immeuble', models.CharField(max_length=50, null=True)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('numcompte', models.CharField(max_length=50, null=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcore.Banque')),
                ('pays_residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.Country')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('date_valeur', models.DateField()),
                ('debut_periode', models.DateField()),
                ('fin_periode', models.DateField()),
                ('nature', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[('ANNULLEE', 'ANNULEE'), ('EN ATTENTE DE REGLEMENT', 'EN ATTENTE DE REGLEMENT'), ('REGLEE', 'REGLEE'), ('EN RETARD DE REGLEMENT', 'RETARD DE REGLEMENT')], default='EN ATTENTE DE REGLEMENT')),
                ('date_statut', models.DateField()),
                ('motif_annulation', models.CharField(max_length=256, null=True)),
                ('contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Contrat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=50)),
                ('date_reglement', models.DateField()),
                ('date_valeur', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[(0, 'ANNULE'), (1, 'REGLE')], default=1)),
                ('date_statut', models.DateField()),
                ('regle_par', models.CharField(max_length=100)),
                ('num_telephone', models.CharField(max_length=50)),
                ('mode_reglement', models.CharField(max_length=100)),
                ('reference_transaction', models.CharField(max_length=50)),
                ('quittance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcore.Quittance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('raison_social', models.CharField(max_length=150)),
                ('num_telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=150, null=True)),
                ('logo', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocieteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societe_users', to='mcore.Societe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societe_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StructureAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('nbre', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=256)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_appartement', to='mcore.Appartement')),
                ('composant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_appartement', to='mcore.ComposantAppartement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='societe',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', through='mcore.SocieteUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcore.Proprietaire'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcore.Immeuble'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='structure',
            field=models.ManyToManyField(related_name='structure', through='mcore.StructureAppartement', to='mcore.ComposantAppartement'),
        ),
    ]
