# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 11:52

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quittance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('date_reglement', models.DateField()),
                ('date_valeur', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[(0, 'ANNULE'), (1, 'REGLE')], default=1)),
                ('date_statut', models.DateField()),
                ('regle_par', models.CharField(max_length=100)),
                ('num_telephone', models.CharField(max_length=50)),
                ('mode_reglement', models.CharField(max_length=100)),
                ('reference_transaction', models.CharField(max_length=50)),
                ('quittance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quittance.Quittance')),
            ],
        ),
    ]
