# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
