# Generated by Django 2.1.7 on 2019-04-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181228_0829'),
        ('client', '0002_auto_20190112_1828'),
    ]

    operations = [
    ]
