# Generated by Django 2.1.7 on 2019-04-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_merge_20190409_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addresse',
        ),
        migrations.AddField(
            model_name='client',
            name='banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banque.Banque'),
        ),
        migrations.AddField(
            model_name='client',
            name='ice_contact',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ice_number',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ice_relation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
