default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-docstrings',
                                'flake8-eradicate',
                                'flake8-polyfill',
                                'flake8-print']
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: check-merge-conflict
    - id: check-json
    - id: double-quote-string-fixer
    - id: check-ast
    - id: check-added-large-files
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.2.0
  hooks:
    - id: reorder-python-imports
