FROM rabbitmq:3-management

# Define environment variables.
ENV RABBITMQ_USER tenancia
ENV RABBITMQ_PASSWORD myrabbitpass
ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq

ADD init_rabbitmq.sh /init_rabbitmq.sh
RUN chmod +x /init_rabbitmq.sh
EXPOSE 15672

# Define default command
CMD ["/init_rabbitmq.sh"]
