# Generated by Django 2.0.2 on 2018-07-12 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=50)),
                ('nb_sejour', models.IntegerField(null=True)),
                ('nb_chambre', models.IntegerField(null=True)),
                ('nb_salle_a_manger', models.IntegerField(null=True)),
                ('nb_cuisine', models.IntegerField(null=True)),
                ('nb_douche', models.IntegerField(null=True)),
                ('autre_description', models.TextField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('codebanque', models.CharField(max_length=25)),
                ('libbanque', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('ice', models.CharField(max_length=100, null=True)),
                ('ice_number', models.CharField(max_length=50, null=True)),
                ('ice_relation', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('reference_bail', models.CharField(max_length=50)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('duree', models.IntegerField()),
                ('periodicite', models.IntegerField()),
                ('montant_bail', models.IntegerField()),
                ('statut', models.IntegerField(choices=[(0, 'ANNULE'), (1, 'PROPOSITION'), (2, 'EN COURS'), (3, 'RESILIE'), (4, 'TERME')], default=1)),
                ('caution', models.IntegerField()),
                ('caution_eau', models.IntegerField()),
                ('caution_electricite', models.IntegerField()),
                ('observation', models.CharField(max_length=256, null=True)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Appartement')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('date_valeur', models.DateField()),
                ('debut_periode', models.DateField()),
                ('fin_periode', models.DateField()),
                ('nature', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[(0, 'ANNULE'), (1, 'EN ATTENTE DE REGLEMENT'), (2, 'REGLEE'), (3, 'RETARD DE REGLEMENT')], default=1)),
                ('date_statut', models.DateField()),
                ('contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Contrat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512, null=True)),
                ('adresse', models.CharField(max_length=512, null=True)),
                ('jour_emission_facture', models.IntegerField(default=5)),
                ('jour_valeur_facture', models.IntegerField(default=5)),
                ('ville', models.CharField(max_length=128, null=True)),
                ('quartier', models.CharField(max_length=128, null=True)),
                ('ref_immeuble', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('numcompte', models.CharField(max_length=50, null=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Banque')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=50)),
                ('date_reglement', models.DateField()),
                ('date_valeur', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[(0, 'ANNULE'), (1, 'REGLE')], default=1)),
                ('date_statut', models.DateField()),
                ('regle_par', models.CharField(max_length=100)),
                ('num_telephone', models.CharField(max_length=50)),
                ('mode_reglement', models.CharField(max_length=100)),
                ('reference_transaction', models.CharField(max_length=50)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcore.Facture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcore.Proprietaire'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcore.Immeuble'),
        ),
    ]
