# Generated by Django 2.0.2 on 2018-08-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='codebanque',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
