# Generated by Django 2.0.2 on 2018-08-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcore', '0002_auto_20180811_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banque',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
