# Generated by Django 2.0.2 on 2018-08-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcore', '0004_auto_20180815_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='caution',
            new_name='caution_loyer',
        ),
    ]
