version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:10.5
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
      DJANGO_SECRET_KEY: test
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: config.settings.test
    working_directory: ~/meslimmo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Create LOGS Directory (if not exists)
          command: |
            sudo mkdir -m777 -p ~/meslimmo/LOGS
      # Step 3: run linter and tests
      # flake8 --exclude=venv* --statistics
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v