# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartement', '0004_auto_20190630_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('autre_description', models.TextField(max_length=1024)),
                ('statut', models.CharField(choices=[('LIBRE', 'LIBRE'), ('RESERVE', 'RESERVE'), ('OCCUPE', 'OCCUPE'), ('BIENTOT LIBRE', 'BIENTOT_LIBRE')], default='LIBRE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512, null=True)),
                ('adresse', models.CharField(max_length=512, null=True)),
                ('jour_emission_facture', models.IntegerField(default=5)),
                ('jour_valeur_facture', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Immeuble',
                'verbose_name_plural': 'Immeubles',
            },
        ),
        migrations.CreateModel(
            name='StructureAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=256)),
                ('is_periodic', models.BooleanField(default=False)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scaffolding_appartement', to='scaffolding.Appartement')),
                ('composantAppartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scaffolding_composant_appartement', to='appartement.ComposantAppartement')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scaffolding.Immeuble'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='structure',
            field=models.ManyToManyField(related_name='scaffolding_structure', through='scaffolding.StructureAppartement', to='appartement.ComposantAppartement'),
        ),
    ]
