# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('autre_description', models.TextField(max_length=1024)),
                ('statut', models.CharField(choices=[('LIBRE', 'LIBRE'), ('RESERVE', 'RESERVE'), ('OCCUPE', 'OCCUPE'), ('BIENTOT LIBRE', 'BIENTOT_LIBRE')], default='LIBRE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComposantAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('utilite', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=256)),
                ('is_periodic', models.BooleanField(default=False)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartement', to='appartement.Appartement')),
                ('composantAppartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composant_appartement', to='appartement.ComposantAppartement')),
            ],
        ),
    ]
