# Generated by Django 2.1.4 on 2018-12-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeuble', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('autre_description', models.TextField(max_length=1024)),
                ('statut', models.CharField(choices=[('LIBRE', 'LIBRE'), ('RESERVE', 'RESERVE'), ('OCCUPE', 'OCCUPE'), ('BIENTOT LIBRE', 'BIENTOT_LIBRE')], default='LIBRE', max_length=50)),
                ('immeuble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immeuble.Immeuble')),
            ],
        ),
        migrations.CreateModel(
            name='ComposantAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('utilite', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StructureAppartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=256)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_appartement', to='appartement.Appartement')),
                ('composant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_appartement', to='appartement.ComposantAppartement')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='structure',
            field=models.ManyToManyField(related_name='structure', through='appartement.StructureAppartement', to='appartement.ComposantAppartement'),
        ),
    ]
