# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeuble', '0001_initial'),
        ('appartement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='immeuble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immeuble.Immeuble'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='structure',
            field=models.ManyToManyField(related_name='structure', through='appartement.StructureAppartement', to='appartement.ComposantAppartement'),
        ),
    ]
