# Generated by Django 2.1.7 on 2019-04-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0002_auto_20190402_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureappartement',
            name='appartement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartement', to='appartement.Appartement'),
        ),
        migrations.AlterField(
            model_name='structureappartement',
            name='composantAppartement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composant_appartement', to='appartement.ComposantAppartement'),
        ),
    ]
