# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0003_auto_20190408_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureappartement',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='composantappartement',
            name='utilite',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
