# Generated by Django 2.1.2 on 2018-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0002_auto_20181015_2325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
