# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartement', '0004_auto_20190630_1534'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesoireloyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('utilite', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_bail', models.CharField(max_length=50)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('periodicite', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('montant_bail', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('statut', models.CharField(choices=[('ANNULE', 'ANNULE'), ('PROPOSITION', 'PROPOSITION'), ('EN COURS', 'EN COURS'), ('RESILIE', 'RESILIE'), ('TERME', 'TERME')], default='PROPOSITION', max_length=64)),
                ('observation', models.CharField(max_length=256, null=True)),
                ('tacite_reconduction', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratAccessoiresloyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('is_periodic', models.BooleanField(default=True)),
                ('devise', models.CharField(default='XOF', max_length=256)),
                ('statut', models.CharField(default='NON PAYE', max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('accesoireloyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesoireloyer', to='contrat.Accesoireloyer')),
                ('contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrat', to='contrat.Contrat')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='accessoires',
            field=models.ManyToManyField(related_name='accessoires', through='contrat.ContratAccessoiresloyer', to='contrat.Accesoireloyer'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='appartement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appartement.Appartement'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
