# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrataccessoiresloyer',
            name='is_periodic',
        ),
        migrations.AddField(
            model_name='contrataccessoiresloyer',
            name='is_peridic',
            field=models.BooleanField(default=False),
        ),
    ]
