# Generated by Django 2.1.7 on 2019-04-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant_bail',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='contrataccessoiresloyer',
            name='montant',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
