# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrataccessoiresloyer',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrataccessoiresloyer',
            name='statut',
            field=models.CharField(choices=[('NOT PAID', 'NON PAYE'), ('PAID', 'PAID')], default='NOT PAID', max_length=256),
        ),
    ]
