# Generated by Django 2.1.7 on 2019-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_auto_20190417_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('ANNULE', 'ANNULE'), ('PROPOSITION', 'PROPOSITION'), ('EN COURS', 'EN COURS'), ('RESILIE', 'RESILIE'), ('TERME', 'TERME')], default='PROPOSITION', max_length=64),
        ),
    ]
