# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_auto_20190602_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant_bail',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
