# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat', '0002_auto_20190701_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('date_valeur', models.DateField()),
                ('debut_periode', models.DateField()),
                ('fin_periode', models.DateField()),
                ('nature', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.IntegerField(choices=[('ANNULLEE', 'ANNULEE'), ('EN ATTENTE DE REGLEMENT', 'EN ATTENTE DE REGLEMENT'), ('REGLEE', 'REGLEE'), ('EN RETARD DE REGLEMENT', 'RETARD DE REGLEMENT')], default='EN ATTENTE DE REGLEMENT')),
                ('date_statut', models.DateField()),
                ('motif_annulation', models.CharField(max_length=256, null=True)),
                ('contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contrat.Contrat')),
            ],
        ),
    ]
