# Generated by Django 2.1.7 on 2019-04-08 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=150)),
                ('num_telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=150, null=True)),
                ('logo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SocieteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societe_users', to='societe.Societe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societe_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='societe',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', through='societe.SocieteUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
