# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societeusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='societeusers',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
