# Generated by Django 2.1.2 on 2018-12-28 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(max_length=50)),
                ('numcompte', models.CharField(max_length=50, null=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banque.Banque')),
                ('pays_residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.Country')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
