# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='address_proprio',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='phone_number',
        ),
    ]
