# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0002_auto_20190508_1501'),
    ]

    operations = [

    ]
