# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0002_auto_20190525_2355'),
        ('proprietaire', '0002_auto_20190508_1501'),
    ]

    operations = [
    ]
